apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gatekeeper-operator
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper-operator-ns
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-gatekeeper-operator
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper-operator-catalog-source
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: gatekeeper-operator
                  namespace: openshift-gatekeeper-operator
                spec:
                  displayName: Gatekeeper Operator Upstream
                  image: quay.io/gatekeeper/gatekeeper-operator-bundle-index:latest
                  publisher: github.com/font/gatekeeper-operator
                  sourceType: grpc
                  updateStrategy:
                    registryPoll:
                      interval: 45m
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper-operator-group
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: gatekeeper-operator
                  namespace: openshift-gatekeeper-operator
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper-operator-subscription
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: gatekeeper-operator-sub
                  namespace: openshift-gatekeeper-operator
                spec:
                  channel: stable
                  name: gatekeeper-operator
                  source: gatekeeper-operator
                  sourceNamespace: openshift-gatekeeper-operator
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gatekeeper
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.gatekeeper.sh/v1alpha1
                kind: Gatekeeper
                metadata:
                  name: gatekeeper
                spec:
                  audit:
                    logLevel: INFO
                    replicas: 1
                  image:
                    image: docker.io/openpolicyagent/gatekeeper:v3.3.0
                  mutatingWebhook: Disabled
                  validatingWebhook: Enabled
                  webhook:
                    emitAdmissionEvents: Enabled
                    logLevel: INFO
                    replicas: 2
          remediationAction: inform
          severity: high
  remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-gatekeeper-operator
  namespace: acm-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-policy-gatekeeper-operator
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-gatekeeper-operator
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
    open-cluster-management.io/user-identity: Z29raGFu
  name: placement-policy-gatekeeper-operator
  namespace: acm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - ocy